### ISSUE TITLE
'reveal' all animations without need to scroll?

### ISSUE THREAD

**Issue by dtate888** [jlmakes/scrollreveal.js#229] opened 2016-02-06 02:12 UTC
**feature request**
I know that scrolling is in the name, but in actuality we just want the animations to appear in a sequence on page load, even if it manages to be (just outside of) the viewport. I guess this might be a duplicate of #215 . Basically, I'm just using scrollreveal as an effects library, and I want to be able to 'trigger' the effect.

**Comment by jlmakes** [comment] 2016-02-06 12:06
Hi @dtate888 

It’s actually an exact duplicate of #145 :wink: but thank you for looking before opening an issue. The solution is very straight forward, **the element should be considered visible no matter where it is.**

So our `_isElemVisible` method goes from all this biz...
```js
function _isElemVisible( elem ){
  var offset     = _getOffset( elem.domEl );
  var container  = _getContainer( elem.config.container );
  var scrolled   = _getScrolled( elem.config.container );
  var vF         = elem.config.viewFactor;
  // Define the element geometry.
  var elemHeight = offset.height;
  var elemWidth  = offset.width;
  var elemTop    = offset.top;
  var elemLeft   = offset.left;
  var elemBottom = elemTop  + elemHeight;
  var elemRight  = elemLeft + elemWidth;

  return ( confirmBounds() || isPositionFixed() );

  function confirmBounds(){
    // Define the element functional boundaries, including the viewFactor.
    var top        = elemTop    + elemHeight * vF;
    var left       = elemLeft   + elemWidth  * vF;
    var bottom     = elemBottom - elemHeight * vF;
    var right      = elemRight  - elemWidth  * vF;
    // Define the container boundaries.
    var viewTop    = scrolled.y + elem.config.viewOffset.top;
    var viewLeft   = scrolled.x + elem.config.viewOffset.left;
    var viewBottom = scrolled.y - elem.config.viewOffset.bottom + container.height;
    var viewRight  = scrolled.x - elem.config.viewOffset.right  + container.width;
    // Check if our element is within bounds.
    return ( top    < viewBottom )
        && ( bottom > viewTop    )
        && ( left   > viewLeft   )
        && ( right  < viewRight  );
  }

  function isPositionFixed(){
    return ( window.getComputedStyle( elem.domEl ).position === 'fixed' );
  }
}
```

To this this biz...
```js
function _isElemVisible( elem ){
  return true;
}
```

**Closed by jlmakes** 2016-02-06 12:06 UTC
Labels: Duplicate, Question

**Comment by dtate888** [comment] 2016-02-06 20:16
You rock sir!
