### ISSUE TITLE
Elements to animate one at a time

### ISSUE THREAD

**Issue by TiagoDeSousa** [jlmakes/scrollreveal.js#234] opened 2016-02-27 14:33 UTC
So I have this:
```js
window.sr = ScrollReveal();
sr.reveal( '.animate', { delay: 700, easing: 'ease', duration: 800, scale: 0 } );
```
and as I scroll down the page all the elements that have the class 'animate' that come on the viewport animate one at a time... great! But how to make each element animate one at a time even if they all come at the same time in the viewport?
Thank you!

**Comment by jlmakes** [comment] 2016-02-27 15:18
Duplicate of #187 #215, please search existing issues before opening a new one.

**Comment by jlmakes** [comment] 2016-03-06 20:39
### New In ScrollReveal v3.1
You can now pass a sequence interval (in milliseconds) to the `reveal()` method, making sequenced animations a breeze.
```js
// interval passed to reveal
window.sr = ScrollReveal({ duration: 2000 });
sr.reveal('.box', 50);

// or...

// interval and custom config passed to reveal
window.sr = ScrollReveal();
sr.reveal('.box', { duration: 2000 }, 50);
```
![sequencer](https://cloud.githubusercontent.com/assets/2044842/13556788/a7dda6c6-e3e2-11e5-93fa-d6a227cbb5dc.gif)

It was a beast to implement, but thanks for the request @TiagoDeSousa :bow:

**Comment by jlmakes** [comment] 2016-03-07 16:45
Closed by https://github.com/jlmakes/scrollreveal.js/commit/3c1b9daf53b61574a12ee87752b3f3ae0580d528

**Closed by jlmakes** 2016-03-07 16:45 UTC
Labels: Duplicate, Feature Request
