### ISSUE TITLE
CSS transition flickers in Safari?

### ISSUE THREAD

**Issue by xavierartot** [jlmakes/scrollreveal.js#214] opened 2016-01-07 20:42 UTC
Hi,
I have a problem in Safari. Look at Our Model section: http://theme-pro.net/baderhouse/

```js
window.sr = new ScrollReveal({ reset: true });

var modelReveal = {
  distance : '20%',
  duration : 800,
  rotate   : { y: 180 }
};

sr.reveal( '.model2, .model3., .model4, .model5, .model6, .model7 ', modelReveal );

sr.reveal( '.model2, .model4, .model6', { origin: 'right' } );
sr.reveal( '.model3, .model5, .model7', { origin: 'left' } );

sr.reveal( '.model2', { delay: 200 } );
sr.reveal( '.model3', { delay: 300 } );
sr.reveal( '.model4', { delay: 400 } );
sr.reveal( '.model5', { delay: 500 } );
sr.reveal( '.model6', { delay: 600 } );
sr.reveal( '.model7', { delay: 700 } );
```

**Comment by jlmakes** [comment] 2016-01-07 23:36
@xavierartot Let’s be clear—**ScrollReveal does work in Safari**, but your site is having rendering issues currently. You can test the [ScrollReveal Demo](https://scrollrevealjs.org/) in Safari (desktop or mobile) to see it working correctly.

Not including jQuery, you have over 73KB of JavaScript. ScrollReveal accounts for ~3KB. I’m not sure what’s causing the problem, but I can only assume it's a 3rd party conflict unless you provide an isolated example of ScrollReveal exhibiting the bug. 

I would first take a look at whatever plugins you may be using for layout, other animations, or that use scroll position. Remove things until it works. Not sure I can be of much help here :bee:

***

#### Let’s Talk Performance

I looked at your site, and you have 85 requests! Your site loaded 1.2MB, plus a 11.3MB video (elderly.mp4) that took my desktop computer 2.6 minutes to complete… and then it makes another request for the same video, loading it all over again!!

This site is responsive, but these performance numbers do not make this mobile friendly _at all_. I strongly urge you, developer to developer, to give some attention to optimizing your site instead of adding another library for animations.

**Comment by xavierartot** [comment] 2016-01-08 00:49
thanks, is on development,and a lot of library going to be gone, the video is a test video no optimize, is not minify and concatenate.
Thanks for your talk, I apreciate.
The problem is from:
{  rotate   : { y: 180 },
when I take of the rotation is working in Safari.

**Comment by jlmakes** [comment] 2016-01-08 01:25
>thanks, is on development,and a lot of library going to be gone, the video is a test video no optimize, is not minify and concatenate. Thanks for your talk, I appreciate it.

Sure, I can understand if it's still in development—just wanted to share my thoughts, cause I was shocked.

>The problem is from `{ rotate : { y: 180 }` when I take off the rotation is working in Safari.

I‘ve tested rotation in Safari as well, and it works fine. The problem must be a 3rd party conflict, or perhaps a CSS issue? Either way, unless you can reproduce it in a [jsbin](jsbin.com) there’s not much I can do for you, or improving the ScrollReveal library.

**Comment by xavierartot** [comment] 2016-01-08 01:54
Thank you I'm digging, thanks

**Comment by jlmakes** [comment] 2016-01-08 07:34
Also, this…
```js
sr.reveal( '.model2', { delay: 200 } );
sr.reveal( '.model3', { delay: 300 } );
sr.reveal( '.model4', { delay: 400 } );
sr.reveal( '.model5', { delay: 500 } );
sr.reveal( '.model6', { delay: 600 } );
sr.reveal( '.model7', { delay: 700 } );
```
Is exactly what #187 #215 are asking for—a better way to sequence animations since this is such a common use case. I’m working on this for the next version of ScrollReveal :bow:

**Comment by jlmakes** [comment] 2016-01-12 01:09
@xavierartot Any luck identifying the rendering error?

**Comment by xavierartot** [comment] 2016-01-12 02:06
I will just unactive it for Safari.

**Comment by jlmakes** [comment] 2016-01-12 04:52
Alright well, I’ve tested rotation and a number of CSS variations and I can’t recreate the bug.

_Here’s it is in Safari:_

![scrollreveal-rotate](https://cloud.githubusercontent.com/assets/2044842/12255097/621bc1a8-b8f0-11e5-9c26-6fbea03d0d3a.gif)

I’m going to close this for now, but if you find a way to recreate the rendering issues please open a new issue with the sample. Thanks! :bow:

**Closed by jlmakes** 2016-01-12 04:52 UTC
Labels: Browser, Question
