### ISSUE TITLE
Can't initialize Library 

### ISSUE THREAD

**Issue by whoisjuan** [jlmakes/scrollReveal.js#183] opened 2015-11-03 23:31 UTC
Hi,

I couldn't find any issue about initializing the library so beforehand sorry if this is repeated.

This is the website in which I'm having the problem: http://whoisjuan.github.io/  (Feel free to inspect it)
It already has all setup and the element that I'm trying to animate is the centered logo in the first section.

The problem is that I can't initialize the library in my project but I don't manage to get the animations working. I'm not getting any error in the console so this could be an issue on the setup of my project.

I searched online and I found someone who had the exact same problem as me and he said he fix it by changing the default configuration. I'm copying and pasting verbatim with my own code because his issue is exactly my issue now:

------------------ 
His comment in the forum (Same problem as me):

"Hello,

I have been trying to get scrollReveall.js to work:

https://github.com/julianlloyd/scrollReveal.js

I have followed the instructions, and It just wont work!

I have some other jquery based javascript sroll events on the page working perfectly fine...i dont usually have issue with stuff like this, but its been 4 hours trying to get this to work, and I am so upset!

WHAT I HAVE DONE:

As per instructions I have added the following to the HEAD:

1)
```html
<script type='text/javascript' src='assets/js/scrollReveal.min.js'></script>
```

2)
```html
<script>

      window.sr = new scrollReveal();

    </script>
```

3) Looking on the Home Page of the website, at the top jumbotron area, I tried added the exact code example snippet that they give on their github page:

```html
<div class="center-block" data-sr><img src="assets/img/brandred.png" class="center-block img-responsive" alt="whoisjuan"></div>
```
...This has no animation effect.

4) Where I want to use this, is down the page where you see Logos. I have added the same example snippet code to the first logo image, but no effect!

5) On the 'Tips' page on GitHub ( https://github.com/julianlloyd/scrol...l.js/wiki/Tips ) It says to try adding this to the head:

```html
<style> [data-sr] { visibility: hidden; } </style>
```

...but this doesnt work either, it just hides any elements with 'data-sr'."

----------------

In that same forum he later mentioned this:

"I got it working eventually.

The issue was a setting in the default config that wouldn't let the example animation code animate. I found this out by accident!" "

----------------

I already tried passing a new config (I just changed the node of the viewport and the reset value) but it didn't work.

Any idea what might be the issue here?

**Comment by jlmakes** [comment] 2015-11-04 08:20
So, you correctly included the script in the head (step 1) — but when you instantiate ScrollReveal, you need to make sure you do this *after* the DOM has loaded.

The problem is that you are calling `new scrollReveal()` in the `<head>` which will fire before the rest of the DOM is loaded… meaning your logo with `data-sr` doesn’t exist yet.

**If you move the instantiation (step 2) to the bottom of your document, just before the closing `</body>` tag, you should find everything working as expected.**

For future reference, this is something you’ll want to keep in mind as you write any JavaScript—it’s usually a good idea to put all your custom JavaScript *after* all your body content.

Or, sometimes you’ll see this code in jQuery:
```js
$(document).ready(function(){
  console.log("Ready!");
}):

// Shorthand for $( document ).ready()
$(function(){
  console.log("Ready!");
});
```
This is another way (using jQuery) to make sure your JavaScript runs *after* the DOM is available. For something like this, it doesn’t matter where you write your JavaScript… but I would still recommend putting your JavaScript at the bottom.

The only scripts you want in the `<head>` of your document are things like **jQuery** or **Modernizr**, libraries that you specifically need first as a page is loading.

**Closed by jlmakes** 2015-11-04 08:20 UTC
Labels: Question

**Comment by whoisjuan** [comment] 2015-11-04 15:03
Awesome!! Thank you very much!

**Comment by Maxhodges** [comment] 2015-11-21 19:02
I also can't get it working. tried all of the above. using 3.0RC'

**Comment by whoisjuan** [comment] 2015-11-22 05:01
It worked for me. Try to follow the steps provided by Julian. My problem
was instantiating SR before the DOM loads so make sure you have the
scrollReveal() just before the closing body tag. That solved the problem
for me.

If you already tried all these things maybe there's something wrong with
your files. Have you checked your console to see if it's giving you an
error?
