### ISSUE TITLE
Add "main" entry to bower.json

### ISSUE THREAD

**Issue by ethanmay** [jlmakes/scrollreveal.js#199] opened 2015-12-21 15:22 UTC
For automatic dependency injection like grunt's wiredep task, please add the following line to .bower.json

`"main": "dist/scrollreveal.js"`

Thanks!!!

**Comment by jlmakes** [comment] 2015-12-21 19:24
`String` or `Array of String` are both valid `main` value types, and this already exists...

_bower.json_

```js
{
  "name"        : "scrollreveal",
  "description" : "Easy scroll animations for web and mobile browsers.",
  "homepage"    : "https://scrollrevealjs.org",
  "main"        : ["dist/scrollreveal.js"],
  "authors"     : ["Julian Lloyd"],
  "license"     : "MIT",

  "keywords": [
    "scroll",
    "reveal",
    "css",
    "animation",
    "javascript",
    "mobile"
  ],

  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "app/bower_components"
  ]
}
```

**Comment by jlmakes** [comment] 2015-12-22 00:46
You must be on to something @ethanmay…

<img width="933" alt="screen shot 2015-12-22 at 1 44 26 am" src="https://cloud.githubusercontent.com/assets/2044842/11945240/aa050d0c-a84d-11e5-88bf-15e960b15a84.png">

Apparently `invalid-meta` for `main` and `ignore`.

**Comment by jlmakes** [comment] 2015-12-22 01:10
I’ve used [bower-json](https://github.com/bower/json#readfile-options-callback) to check the file, and no errors are thrown… got any ideas?

**Comment by ethanmay** [comment] 2015-12-22 01:39
When I ran `bower install scrollreveal --save`, scrollreveal contains a `.bower.json` file. Notice that this is a hidden file, and not `bower.json`, which incidentally isn't generated when I run this command. This is the contents of `.bower.json`:

```
{
  "name": "scrollreveal",
  "homepage": "https://github.com/jlmakes/scrollreveal.js",
  "version": "3.0.1",
  "_release": "3.0.1",
  "_resolution": {
    "type": "version",
    "tag": "v3.0.1",
    "commit": "6fc1af488b9cec5763e998efbbee8864d3892555"
  },
  "_source": "git://github.com/jlmakes/scrollreveal.js.git",
  "_target": "~3.0.1",
  "_originalSource": "scrollreveal",
  "_direct": true
}
```

To fix this in my install, I added the line I mentioned in my original comment. The result was functional (I'm using yeoman with generator-angular to test), and injected scrollreveal properly. Here is the `.bower.json` file I used:

```
{
  "name": "scrollreveal",
  "homepage": "https://github.com/jlmakes/scrollreveal.js",
  "version": "3.0.1",
  "_release": "3.0.1",
  "_resolution": {
    "type": "version",
    "tag": "v3.0.1",
    "commit": "6fc1af488b9cec5763e998efbbee8864d3892555"
  },
  "_source": "git://github.com/jlmakes/scrollreveal.js.git",
  "_target": "~3.0.1",
  "_originalSource": "scrollreveal",
  "_direct": true,
  "main": "dist/scrollreveal.js"
}
```

**Comment by jlmakes** [comment] 2015-12-22 01:59
`.bower.json` is a duplicate of the original `bower.json` used by Bower, with additional meta data.

My current theory is that since `bower.json` is omitted from the release (due to an `export-ignore` inside the repo `.gitattributes`), it's not capturing any of the original `bower.json`—just using package defaults and the added meta data.

@ethanmay I’ve opened an issue here: https://github.com/bower/bower/issues/2115

Perhaps someone can confirm this, in which case I will remove `bower.json export-ignore` from the `.gitattributes` for future versions of ScrollReveal.

**Closed** 2015-12-22 06:17 UTC
Labels: Fix / Improvement

**Comment by jlmakes** [comment] 2015-12-22 06:19
No warnings anymore, looks like my hunch was correct.

<img width="942" alt="screen shot 2015-12-22 at 7 18 32 am" src="https://cloud.githubusercontent.com/assets/2044842/11949143/40fc5836-a87c-11e5-9b2c-fb97df743223.png">
